//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
    },
  },
  {
    // `convex/_generated` is regenerated by the CLI, `.output`, `.vercel` and `dist` are build
    // artefacts: none belongs to the linter's TypeScript project, and its typed parser fails on
    // their `.js` files. Without this, a single `npm run build` breaks `npm run lint` — `.vercel`
    // is where the build lands whenever Nitro picks the Vercel preset.
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      'convex/_generated/',
      '.output/',
      '.vercel/',
      'dist/',
    ],
  },
]
