//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
    },
  },
  {
    // `convex/_generated` is regenerated by the CLI and is not part of the linter's TypeScript
    // project: the typed parser fails on its `.js` files.
    ignores: ['eslint.config.js', 'prettier.config.js', 'convex/_generated/'],
  },
]
