//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
    },
  },
  {
    // Moved off `tsc`. `noUnusedLocals`/`noUnusedParameters` also police the vendored `.ts` a
    // component's test helper pulls into the program — `@convex-dev/workpool/test` resolves to
    // `src/`, not `dist/`, and its `const _ = {} as X satisfies Y` idiom trips them. The linter
    // never leaves our own files, so the rule lands where it belongs. `_` prefix stays exempt: the
    // codebase already writes `_ctx` and `_unused` for a signature it must honour but not read.
    //
    // `files` is load-bearing: the shared config registers the `@typescript-eslint` plugin only for
    // that glob, and a rule set to anything but `off` needs its plugin in scope.
    files: ['**/*.{js,ts,tsx}'],
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    // `convex/_generated` is regenerated by the CLI, `.output`, `.vercel` and `dist` are build
    // artefacts: none belongs to the linter's TypeScript project, and its typed parser fails on
    // their `.js` files. Without this, a single `npm run build` breaks `npm run lint` — `.vercel`
    // is where the build lands whenever Nitro picks the Vercel preset.
    // `.claude/worktrees/` holds whole checkouts of this repo: linting them means linting every file
    // twice over, against a `tsconfig` that does not cover them.
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      'convex/_generated/',
      '.claude/',
      '.output/',
      '.vercel/',
      'dist/',
    ],
  },
]
