import { existsSync, realpathSync } from 'node:fs'
import { resolve } from 'node:path'

import { defineConfig, searchForWorkspaceRoot, lazyPlugins } from 'vite-plus'

import { tanstackStart } from '@tanstack/react-start/plugin/vite'

import viteReact from '@vitejs/plugin-react'
import { nitro } from 'nitro/vite'

const projectRoot = process.cwd()
const nodeModules = resolve(projectRoot, 'node_modules')

// A git worktree symlinks node_modules to the main checkout, so its real path falls outside the
// workspace root Vite derives on its own, and Vite 8 then refuses to read the plugin entry files
// it resolves there — `vite dev` dies on ERR_LOAD_URL for files that plainly exist. Allowing the
// resolved node_modules is a no-op in the main checkout, where it already sits under the root.
const fsAllow = [searchForWorkspaceRoot(projectRoot)]
if (existsSync(nodeModules)) fsAllow.push(realpathSync(nodeModules))

const config = defineConfig({
  fmt: {
    // Ported from `prettier.config.js` and `.prettierignore` by `oxfmt --migrate=prettier`.
    // `printWidth` is written down because oxfmt defaults to 100 where Prettier defaulted to 80:
    // left implicit, the whole tree would reflow.
    semi: false,
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 80,

    // Off by default in Prettier, and this repository never sorted `package.json`: turning it on here
    // would reorder the file on the next `pnpm format`.
    sortPackageJson: false,

    ignorePatterns: [
      'package-lock.json',
      'pnpm-lock.yaml',
      'yarn.lock',

      // Convex codegen: reformatting these files is undone by the next `convex dev`.
      'convex/_generated',

      // Local worktrees: whole checkouts of this repository, already checked where they live.
      '.claude',

      // Spike T1 artefacts: raw harness output, compared byte for byte.
      'spike/fixtures/runs',
      'spike/ladder.*.json',

      // Replay of prompt v3 (step 6): raw output, compared byte for byte against the v2 archive.
      'spike/runs-v3',

      // Generated backup: the order and bytes of these files are controlled by the script. Only the
      // JSON, so that `backup/README.md` stays formatted like the rest of the prose.
      'backup/*.json',
    ],
  },
  lint: {
    // Ported from `@tanstack/eslint-config` by `npx @oxlint/migrate --with-nursery --type-aware`.
    // Three rules had no oxlint equivalent and are gone: `@typescript-eslint/naming-convention`,
    // `node/prefer-node-protocol`, `no-restricted-syntax` — none of them was carrying a decision of
    // ours. The import-sorting rules were already `off` here.
    plugins: ['import', 'typescript', 'react'],

    // The category oxlint enables by default: code that is outright wrong. ESLint gave us none of it,
    // since the shared config never opted into a typed correctness pass.
    categories: {
      correctness: 'error',
    },
    env: {
      builtin: true,
      es2020: true,
      browser: true,
    },

    // `convex/_generated` is regenerated by the CLI, `.output`, `.vercel` and `dist` are build
    // artefacts: none of them is ours to lint. `.claude/worktrees/` holds whole checkouts of this
    // repository — linting them means linting every file twice over.
    ignorePatterns: [
      'convex/_generated/',
      '.claude/',
      '.output/',
      '.vercel/',
      'dist/',
      'coverage/',
    ],
    rules: {
      'for-direction': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-global-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-shadow': 'warn',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-var': 'error',
      'no-with': 'error',
      'prefer-const': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
      'import/first': 'error',
      'import/newline-after-import': 'error',
      'import/no-commonjs': 'error',
      'import/no-duplicates': 'error',
      'typescript/ban-ts-comment': [
        'error',
        {
          'ts-expect-error': false,
          'ts-ignore': 'allow-with-description',
        },
      ],
      'typescript/consistent-type-imports': [
        'error',
        {
          prefer: 'type-imports',
        },
      ],
      'typescript/method-signature-style': ['error', 'property'],
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-for-in-array': 'error',
      'typescript/no-inferrable-types': [
        'error',
        {
          ignoreParameters: true,
        },
      ],
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-unnecessary-condition': 'error',
      'typescript/no-unnecessary-type-assertion': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-for-of': 'warn',
      'typescript/triple-slash-reference': 'error',

      // Moved off `tsc`. `noUnusedLocals`/`noUnusedParameters` also police the vendored `.ts` a
      // component's test helper pulls into the program — `@convex-dev/workpool/test` resolves to
      // `src/`, not `dist/`, and its `const _ = {} as X satisfies Y` idiom trips them. The linter
      // never leaves our own files, so the rule lands where it belongs. `_` prefix stays exempt: the
      // codebase already writes `_ctx` and `_unused` for a signature it must honour but not read.
      'no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // Default `.sort()` is lexicographic, which is exactly what a comparison of two arrays of
      // names wants. The rule is aimed at numbers.
      'typescript/require-array-sort-compare': [
        'error',
        {
          ignoreStringArrays: true,
        },
      ],

      // Both joined the `correctness` category in the oxlint bundled with Vite+ 1.1 (1.87, from
      // 1.78). They flag ref reads during render in `-GestureProgress`, `-IllustrationRow` and
      // `useSearchDraft`, and a synchronous setState in `adminToken`'s effect: code that predates
      // them and works. Off so the toolchain move changes no component; turning them on is its own
      // change, one component at a time.
      'react/refs': 'off',
      'react/set-state-in-effect': 'off',

      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: ['src/shared/**/*.{ts,tsx}'],
        rules: {
          'no-restricted-imports': [
            'error',
            {
              patterns: [
                {
                  group: ['react', 'react-dom', 'react-dom/*', 'react/*'],
                  message:
                    'src/shared runs on both sides: a React import makes it browser-only. Move the module to src/lib.',
                },
                {
                  group: ['**/_generated/*', 'convex/react', '@convex-dev/*'],
                  message:
                    'src/shared is read by the Convex functions themselves: it cannot depend on the generated client. Move the module to src/client.',
                },
                {
                  group: ['../lib/*', '../client/*', '../routes/*'],
                  message:
                    'src/shared is the kernel: it is imported by both sides and depends on neither.',
                },
              ],
            },
          ],
        },
      },
      {
        files: ['convex/**/*.ts'],
        rules: {
          'no-restricted-imports': [
            'error',
            {
              patterns: [
                {
                  group: ['**/src/lib/*', '**/src/client/*', '**/src/routes/*'],
                  message:
                    'A Convex function may only import the kernel: src/shared.',
                },
              ],
            },
          ],
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
  },
  resolve: { tsconfigPaths: true },
  server: { fs: { allow: fsAllow } },
  plugins: lazyPlugins(() => [
    nitro({ rollupConfig: { external: [/^@sentry\//] } }),

    tanstackStart(),
    viteReact(),
  ]),
})

export default config
