/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIllustrationsRouteImport } from './routes/admin_.illustrations'
import { Route as RecetteSlugRouteImport } from './routes/recette.$slug'
import { Route as AdminScanIdRouteImport } from './routes/admin_.scan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIllustrationsRoute = AdminIllustrationsRouteImport.update({
  id: '/admin_/illustrations',
  path: '/admin/illustrations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetteSlugRoute = RecetteSlugRouteImport.update({
  id: '/recette/$slug',
  path: '/recette/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScanIdRoute = AdminScanIdRouteImport.update({
  id: '/admin_/scan/$id',
  path: '/admin/scan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/illustrations': typeof AdminIllustrationsRoute
  '/recette/$slug': typeof RecetteSlugRoute
  '/admin/scan/$id': typeof AdminScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/illustrations': typeof AdminIllustrationsRoute
  '/recette/$slug': typeof RecetteSlugRoute
  '/admin/scan/$id': typeof AdminScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin_/illustrations': typeof AdminIllustrationsRoute
  '/recette/$slug': typeof RecetteSlugRoute
  '/admin_/scan/$id': typeof AdminScanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/illustrations'
    | '/recette/$slug'
    | '/admin/scan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/illustrations'
    | '/recette/$slug'
    | '/admin/scan/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin_/illustrations'
    | '/recette/$slug'
    | '/admin_/scan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminIllustrationsRoute: typeof AdminIllustrationsRoute
  RecetteSlugRoute: typeof RecetteSlugRoute
  AdminScanIdRoute: typeof AdminScanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/illustrations': {
      id: '/admin_/illustrations'
      path: '/admin/illustrations'
      fullPath: '/admin/illustrations'
      preLoaderRoute: typeof AdminIllustrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recette/$slug': {
      id: '/recette/$slug'
      path: '/recette/$slug'
      fullPath: '/recette/$slug'
      preLoaderRoute: typeof RecetteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/scan/$id': {
      id: '/admin_/scan/$id'
      path: '/admin/scan/$id'
      fullPath: '/admin/scan/$id'
      preLoaderRoute: typeof AdminScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminIllustrationsRoute: AdminIllustrationsRoute,
  RecetteSlugRoute: RecetteSlugRoute,
  AdminScanIdRoute: AdminScanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
